version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run: 
        working_directory: backend
        command: dotnet build 


workflows:
  build_and_test:
    jobs:
      - build
  welcome:
    jobs:
      - welcome/run
