version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
    steps:
      - checkout
      - run: 
          name: Builind server
          command: 'pwd && dotnet build .'
          working_directory: $CIRCLE_WORKING_DIRECTORY/backend

workflows:
  build_and_test:
    jobs:
      - build
  welcome:
    jobs:
      - welcome/run
