version: 2.1

jobs:
  version: 2
  build-and-seed-database:
    machine: true
    steps:
      - checkout
      - run:
          name: Logging to Docker Hub
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: 
          name: Building image
          working_directory: docker/
          command: docker build -t $DOCKER_USER/risk-management-tool-db:latest
      - run:
          name: Push to Docker Hub
          command: docker push $DOCKER_USER/risk-management-tool-db:latest
  test-backend:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
      - image: jantechner/risk-management-tool-db:latest
    steps:
      - checkout
      - run: 
          name: Building server
          working_directory: backend
          command: 'dotnet build'
      - run:
          name: Run server
          working_directory: backend
          command: 'dotnet run localhost 5432'
  build-frontend: 
    docker:
      - image: node:13-alpine
    steps:
      - checkout
      - run: 
          name: Building frontend
          working_directory: frontend/riskManagementTool
          command: "npm install && npm run build"
          
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-seed-database-image
      - build-frontend
      - build-and-test-backend:
          requires:
            - build-and-seed-database-image
      
